# WARNING: Do not EDIT or MERGE this file, it is generated by 'packagespec lock'.
FROM debian@sha256:bcf83fd8af414eda0c0a99d25a4e61dedd88e7aac7f7bc519d04555ff0c40ec5
COPY . ./
RUN apt-get update -y && apt-get install --no-install-recommends -y -q \
                         curl \
                         zip \
                         build-essential \
                         gcc-multilib \
                         g++-multilib \
                         ca-certificates \
                         git mercurial bzr \
                         gnupg \
                         libltdl-dev \
                         libltdl7 \
						             bash \
                      && rm -rf /var/lib/apt/lists/*